name: QuickDeposit
main: quickdepositpackage.Main
version: 1.0.4
description: Plugin allowing quick despoiting of items into chests

commands:
  heal:
    description: Heals you to full health
    usage: /<command>
  feed:
    description: Feeds you to full hunger
    usage: /<command>
  jester:
    description: Sets your rank to the Jester rank
    usage: /<command>
  squire:
    description: Sets your rank to the Squire rank
    usage: /<command>